modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/KCFindstr/nicebowl-mod/issues"
license = "GPL-3.0"

[[mods]]
modId = "nicebowl"
version = "${version}"
displayName = "NiceBowl"
authors = "KCFindstr"
description = '''
Adds a nice bowl to the game.
'''
logoFile = "nicebowl.png"

[[dependencies.nicebowl]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nicebowl]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nicebowl]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
