modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/KCFindstr/nicebowl-mod/issues"
license = "GPL-3.0"

[[mods]]
modId = "nicebowl"
version = "${version}"
displayName = "NiceBowl"
authors = "KCFindstr"
description = '''
Adds a nice bowl to the game.
'''
logoFile = "nicebowl.png"

[[dependencies.nicebowl]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nicebowl]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nicebowl]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "nicebowl.mixins.json"
